import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { AppShell } from "@/components/layout/AppShell";
import { Toaster } from "sonner";
import { Analytics } from "@vercel/analytics/next";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
  display: "swap",
});

const baseUrl = process.env.NEXT_PUBLIC_APP_URL || "https://www.tryopenslide.com";

export const metadata: Metadata = {
  metadataBase: new URL(baseUrl),

  title: {
    default: "OpenSlide — All-in-One AI Workspace for Slides, Docs, Sheets & Sites",
    template: "%s | OpenSlide",
  },

  description:
    "The all-in-one AI workspace for slides, documents, spreadsheets, and websites. Generate on-brand work from a single prompt. Export to PDF & PPTX. Free to start.",

  keywords: [
    // Workspace / category
    "ai workspace",
    "all in one ai workspace",
    "ai productivity tool",
    "ai content workspace",
    "openslide",
    // Slides
    "ai presentation maker",
    "ai slide generator",
    "ai pitch deck builder",
    "ai powerpoint generator",
    "ai pptx maker",
    "ai deck builder",
    "presentation ai tool",
    "slide deck ai",
    "presentation design ai",
    "automatic slide creator",
    "startup pitch deck maker",
    // Docs
    "ai document builder",
    "ai document generator",
    "ai report writer",
    "ai proposal generator",
    "business proposal generator",
    "ai brief generator",
    // Sheets
    "ai spreadsheet builder",
    "ai spreadsheet generator",
    "ai excel generator",
    "ai financial model builder",
    "ai dashboard generator",
    // Websites
    "ai website builder",
    "ai landing page generator",
    "ai microsite builder",
    "ai web page generator",
    // Brand
    "ai brand kit generator",
    "on-brand ai presentations",
    "branded ai content",
    "ai from pptx",
  ],

  authors: [{ name: "OpenSlide Team", url: baseUrl }],
  creator: "OpenSlide",
  publisher: "OpenSlide",

  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  // Note: og:image and twitter:image are auto-generated by Next.js from
  // src/app/opengraph-image.png and src/app/twitter-image.png — content-hashed
  // URLs so social platforms re-fetch on every deploy that changes the image.
  openGraph: {
    type: "website",
    locale: "en_US",
    url: baseUrl,
    siteName: "OpenSlide",
    title: "OpenSlide — Your All-in-One AI Workspace",
    description:
      "Slides, documents, spreadsheets, and websites — generated on-brand from a single prompt. The all-in-one AI workspace.",
  },

  twitter: {
    card: "summary_large_image",
    title: "OpenSlide — Your All-in-One AI Workspace",
    description:
      "Slides, docs, sheets, and websites — generated on-brand from a single prompt.",
    creator: "@openslideai",
  },

  alternates: {
    canonical: baseUrl,
  },

  category: "Technology",
};

// ─── Structured Data (JSON-LD) ──────────────────────────────────────────────

const websiteJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: "OpenSlide",
  url: baseUrl,
  description:
    "All-in-one AI workspace that generates on-brand slides, documents, spreadsheets, and websites from a single prompt. Export to PDF and PPTX.",
  potentialAction: {
    "@type": "SearchAction",
    target: {
      "@type": "EntryPoint",
      urlTemplate: `${baseUrl}/search?q={search_term_string}`,
    },
    "query-input": "required name=search_term_string",
  },
};

const organizationJsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "OpenSlide",
  url: baseUrl,
  logo: `${baseUrl}/api/icon?size=512`,
  sameAs: [
    "https://twitter.com/openslideai",
    "https://www.linkedin.com/company/openslide",
  ],
  contactPoint: {
    "@type": "ContactPoint",
    contactType: "Customer Support",
    url: `${baseUrl}/contact`,
  },
};

const softwareJsonLd = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "OpenSlide",
  applicationCategory: "BusinessApplication",
  operatingSystem: "Web",
  url: baseUrl,
  description:
    "All-in-one AI workspace for slides, documents, spreadsheets, and websites. Generates on-brand output from a single prompt, with brand-kit extraction from PPTX, PDF and PPTX export, and live in-browser website preview.",
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
    description: "Free tier with 150 credits included",
  },
  aggregateRating: {
    "@type": "AggregateRating",
    ratingValue: "4.8",
    ratingCount: "120",
    bestRating: "5",
  },
  featureList: [
    "AI slide and pitch deck generation from text prompts",
    "AI document and report generation",
    "AI spreadsheet, model, and dashboard generation",
    "AI website and landing page generation",
    "Brand kit extraction from PPTX and PDF",
    "On-brand output across slides, docs, sheets, and websites",
    "PDF and PPTX export",
    "Live in-browser website preview and click-to-edit",
    "Image search and AI image generation",
    "Vision-driven self-review and refinement",
  ],
};

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "What is OpenSlide?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "OpenSlide is an all-in-one AI workspace that generates four formats from a single prompt: slides (pitch decks, board reports, lectures), documents (briefs, reports, proposals), spreadsheets (financial models, trackers, dashboards), and websites (landing pages, microsites, MVPs). Every output ships on-brand when a brand kit is connected.",
      },
    },
    {
      "@type": "Question",
      name: "What can OpenSlide create?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Slides and pitch decks, written documents and reports, spreadsheets and financial models, and live websites and landing pages — all generated by AI from natural-language prompts.",
      },
    },
    {
      "@type": "Question",
      name: "Can OpenSlide build websites?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Yes. OpenSlide's website mode runs entirely in your browser via WebContainer — no setup, no server. Describe a landing page, product site, or microsite and the AI builds it, previews it live, and lets you click any element to edit it.",
      },
    },
    {
      "@type": "Question",
      name: "Can OpenSlide generate documents and spreadsheets?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Yes. Document mode produces briefs, reports, proposals, and long-form writing. Sheets mode produces spreadsheets, financial models, trackers, and dashboards. Both work from a single prompt and respect your brand kit.",
      },
    },
    {
      "@type": "Question",
      name: "Can I export my presentations as PPTX or PDF?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Yes. OpenSlide supports both PDF and PPTX export. PDF exports are vector-based with selectable text. PPTX exports are pixel-perfect images per slide for maximum compatibility.",
      },
    },
    {
      "@type": "Question",
      name: "Is OpenSlide free to use?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Yes, every new account gets 150 free credits. A typical presentation costs about 50-75 credits. You can purchase additional credit packs or upgrade to a paid plan for more credits.",
      },
    },
    {
      "@type": "Question",
      name: "Can I use my company branding?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Yes. Upload your company's PPTX or PDF template and OpenSlide automatically extracts your brand colors, fonts, logos, and layout patterns into a reusable brand kit. Every future slide, document, spreadsheet, and website generated will ship on-brand.",
      },
    },
  ],
};

// ─── Layout ─────────────────────────────────────────────────────────────────

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable} ${inter.variable}`}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="dns-prefetch" href="https://fonts.googleapis.com" />
      </head>
      <body>
        <AppShell>{children}</AppShell>
        <Toaster position="top-center" expand={false} visibleToasts={3} />
        <Analytics />

        {/* Structured data */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
        />
      </body>
    </html>
  );
}
